# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:

## feed this button
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- script: |
    npm install && npm run build
  displayName: 'npm install & build'
  workingDirectory: 'FeedThisButton\web-widget'

- script: |
    npm run prepare-package
  displayName: 'prepare-package to distribution'
  workingDirectory: 'FeedThisButton\web-widget'

- task: ArchiveFiles@2
  displayName: 'Feedthisbutton: Package to distribuition'
  inputs:
    rootFolderOrFile: 'FeedThisButton\web-widget\temp\'
    includeRootFolder: false
    archiveType: '7z'
    archiveFile: '$(Build.ArtifactStagingDirectory)/feedthisbutton.$(Build.BuildId).7z' 
    replaceExistingArchive: true

- script: |
    npx shx sed -i s/%download-url%/feedthisbutton.$(Build.BuildId).7z/ .\public\index.html
  displayName: 'Adjust download link'
  workingDirectory: 'FeedThisButton\web-widget'

- task: CopyFiles@2
  inputs:
    sourceFolder: 'FeedThisButton\web-widget\public'
    contents: '**'
    targetFolder: 'Source\Web Sites\Link.BA.Donate.WebSite\FeedThisButton'

- task: CopyFiles@2
  displayName: 'copy feed this button package to website'
  inputs:
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    contents: 'feedthisbutton.$(Build.BuildId).7z' 
    targetFolder: 'Source\Web Sites\Link.BA.Donate.WebSite\FeedThisButton'
    overWrite: true 

## Alimente esta ideia
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
