# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- feature/*
- features/*
- master
- developer

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  name: Build
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)/dotnetcore'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  name: Test
  inputs:
    command: 'test'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  name: Publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/dotnetcore'
    arguments: '--configuration $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  name: Publish_Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'