# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
variables: 
  ## Add this under variables section in the pipeline
  azureSubscription: banco-alimentar
  ftpServerEndpoint: feedthisbutton-dev

trigger:
- master
stages:
  - stage: Build_publish
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job:
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '12.x'
          displayName: 'Install Node.js'

        - script: |
            npm install
          displayName: 'npm install'
          workingDirectory: web-widget

        - script: |
            npm run build
          displayName: 'build'
          workingDirectory: web-widget

        - task: ArchiveFiles@2
          displayName: 'archive build' 
          inputs:
            rootFolderOrFile: 'web-widget/public' 
            includeRootFolder: false 
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
            replaceExistingArchive: true 

        - task: CopyFiles@2
          displayName: 'copy publish profile' 
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '*.PublishSettings'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
