name: "Build and Test"

on:
  push:
    branches:
      - developer
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - developer
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    name: Build 
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.1
      with:
        dotnet-version: 5.0.x    
    - name: Restore
      run: dotnet restore   
    - name: Build
      run: dotnet build --configuration Release --no-restore -v n
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIAL}}
        enable-AzPSSession: true
    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "alimentaestaideia-key"
        secrets: '*'
      id: devsecrets
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["**/appsettings.json"]'
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["**/appsettings.Development.json"]' 
    - name: Test
      run: dotnet test --no-restore --no-build